<?php ?>

<table id="{$dataTableID}"
       class="table table-striped table-bordered table-hover nowrap"
       cellspacing="0" width="100%">
    <thead>
        <tr>
            {foreach $headers as $key => $row}
            <th
            <?php
             if (isset($row['width'])) {
                 echo 'width="' . str_replace('(px|em|mm)', '', $row['width']) . '"';
             }
            ?>
                id="datatable_{$key}">{$row['name']}</th>
            {/foreach}
        </tr>
    </thead>
    <tbody>
        <?php
         foreach ($rows as $k => $row) {
             ?>
             <tr>
                 <?php
                 foreach ($headers as $key => $head) {
                     ?>
                     <td>
                         <?php
                         if (isset($row[$key])) {

                             $row_val = $row[$key];
                             if (isset($head['transform'])) {
                                 if ($this->presenter->getReflection()->hasMethod($head['transform'])) {
                                     $fce = $head['transform'];
                                     $row_val = $this->presenter->$fce($row[$key]);
                                 }
                             }
                             echo $row_val;
                         } else {
                             if ($this->presenter->getReflection()->hasMethod('action' . ucfirst($key))) {
                                 $module = $this->presenter->makeLink($key);
                                 switch ($key) {
                                     case 'edit':
                                         $button = 'warning';
                                         break;
                                     default:
                                         $button = 'danger';
                                 }
                                 echo '<a href="' . $module . '?id=' . $row['id'] . '" class="btn btn-' . $button . '">' . ucfirst($head['name']) . '</a>';
                             } else {
                                 throw new DataTable\ExceptionDataTable("Metoda " . ucfirst($key) . " neexistuje");
                             }
                         }
                         ?>
                     </td>
                 <?php } ?>
             </tr>
         <?php } ?>
    </tbody>
</table>


{block admin_bottom_scripts}
<script type="text/javascript">
    loadScript(plugin_path + "datatables/js/jquery.dataTables.min.js", function () {
        loadScript(plugin_path + "datatables/js/dataTables.tableTools.min.js", function () {
            loadScript(plugin_path + "datatables/dataTables.bootstrap.js", function () {
                loadScript(plugin_path + "select2/js/select2.full.min.js", function () {

                    var table = jQuery('#<?php echo $dataTableID; ?>');

                    jQuery.extend(true, jQuery.fn.DataTable.TableTools.classes, {
                        "container": "btn-group pull-right tabletools-topbar",
                        "buttons": {
                            "normal": "btn btn-sm btn-default",
                            "disabled": "btn btn-sm btn-default disabled"
                        },
                        "collection": {
                            "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
                        }
                    });
                    var oTable = table.dataTable({
                        "order": [
                            [0, 'asc']
                        ],
                        "lengthMenu": [
                            [5, 15, 20, -1],
                            [5, 15, 20, "All"] // change per page values here
                        ],
                        // set the initial value
                        "pageLength": 10,
                        "tableTools": {
                            "sSwfPath": plugin_path + "datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [{
                                    "sExtends": "pdf",
                                    "sButtonText": "PDF"
                                }, {
                                    "sExtends": "csv",
                                    "sButtonText": "CSV"
                                }, {
                                    "sExtends": "xls",
                                    "sButtonText": "Excel"
                                }, {
                                    "sExtends": "print",
                                    "sButtonText": "Print",
                                    "sInfo": 'Please press "CTR+P" to print or "ESC" to quit',
                                    "sMessage": "Generated by DataTables"
                                }]
                        }
                    });
                    var tableWrapper = jQuery('#<?php echo $dataTableID; ?>_wrapper');
                    tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown

                });
            });
        });
    });
</script>
{/block}
